services:
  - type: web
    name: printqueue
    runtime: python
    buildCommand: bash build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 120
    envVars:
      - key: BAMBU_EMAIL
        sync: false
      - key: BAMBU_PASSWORD
        sync: false
      - key: BAMBU_SERIAL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: BASE_URL
        sync: false
